# -*- coding: utf-8 -*-
"""Week_1_Assignment_WebScrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gF0SGQYXRP_3DUXkSX6yPDIvJcy--3tc

# **iHadis Scrapping**
"""

!pip install requests-html
from requests_html import HTMLSession
session = HTMLSession()

def hadith_book_scrapping(book_name,book_url,total_chapter):
  #book_url = "http://ihadis.com/books"
  for i in range(1, total_chapter+1):
    chapter_url = book_url + "/" + book_name + "/chapter/" + str(i)
    print(chapter_url)
    #chapter_url = http://ihadis.com/books/bukhari/chapter/1
    r = session.get(chapter_url)
    #define pattern
    no_pattern = "div.had > h3.hidden-print"
    arabic_text_pattern = "p.hadith-des2"
    narrator_pattern = "p.narrated-by"
    bangla_text_pattern = "p.hadith-des"
    hadith_status_pattern = ".label.validity"

    numbers = [i.text for i in r.html.find(no_pattern)]
    arabic_text = [i.text for i in r.html.find(arabic_text_pattern)]
    narrator = [i.text for i in r.html.find(narrator_pattern)]
    bangla_text = [i.text for i in r.html.find(bangla_text_pattern)]
    hadith_status =  [i.text for i in r.html.find(hadith_status_pattern)]
    print("Chapter:",i,len(numbers),len(arabic_text),len(narrator),len(bangla_text),len(hadith_status))

    with open(f"{book_name}/{book_name}_chapter_{i}.txt","w") as f:
      f.write("No, Arabic Text, Narrator, Bangla Text, Hadith Status")
      for n, a, na, b, hs in zip(numbers,arabic_text,narrator,bangla_text,hadith_status):
        f.write(f"{n},{a},{na},{b},{hs}")
        f.write("\n")

book_name_list = ["bukhari","muslim","nasayi","abi-dawud","tirmidi","ibn-majah","muatta-malik"]
total_chapter_list = [97,56,50,43,46,37,61]
book_url = "http://ihadis.com/books"

for book_name,total_chapter in zip(book_name_list,total_chapter_list):
  hadith_book_scrapping(book_name,book_url,total_chapter)

